build-base:
	docker build --rm -t edulemasson/spark-base base/

build-master:
	docker build --rm -t edulemasson/spark-master master/

build-worker:
	docker build --rm -t edulemasson/spark-worker worker/

make-submit:
	docker build --rm -t edulemasson/spark-submit submit/